# Copyright (C) 2022 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build and test Cryptonite

on:
  push:
    branches: [ main, cryptonite-ci ]
    paths:
      - ".github/workflows/ci.yml"
      - ".github/workflows/lint.yml"
      - ".github/workflows/make-package.yml"
      - ".github/workflows/run-integration-tests.yml"
      - ".github/workflows/run-unit-tests.yml"
      - "cryptonite/**"
      - "pyproject.toml"
      - "setup.py"

    tags:
      - 'v*.*.*'

  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - ".github/workflows/lint.yml"
      - ".github/workflows/make-package.yml"
      - ".github/workflows/run-integration-tests.yml"
      - ".github/workflows/run-unit-tests.yml"
      - "cryptonite/**"
      - "pyproject.toml"
      - "setup.py"

jobs:
  # The purpose of this workflow is just to call reusable-workflows in the right order
  # and to connect workflow input/outputs when appropriate.

  lint:
    name: Lint project
    uses: ./.github/workflows/lint.yml

  make-package:
    # This job creates an artifact with Cryptonite's package (consisting of wheel and .tar.gz files)
    # This package is used by the test jobs in this workflow as well as by the cd.yml workflow
    name: Package Cryptonite
    needs: lint
    uses: ./.github/workflows/make-package.yml

  run-unit-tests:
    name: Run unit tests
    needs: make-package

    # Run unit tests using different combinations of OS and Python version
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.7", "3.11"]
      fail-fast: false

    uses: ./.github/workflows/run-unit-tests.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      # Install Cryptonite using the artifact generated by the make-package step
      pkg-artifact: ${{ needs.make-package.outputs.pkg-artifact }}

  run-integration-tests:
    name: Run integration tests
    needs: make-package

    # Run integration tests using different combinations of OS and Python version
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.7", "3.11"]
      fail-fast: false

    uses: ./.github/workflows/run-integration-tests.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      # Install Cryptonite using the artifact generated by the make-package step
      pkg-artifact: ${{ needs.make-package.outputs.pkg-artifact }}

# Note that unit and integration tests do not depend on one another, and can thus run in parallel