# Copyright (C) 2022 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build, test and publish Cryptonite

on:
  # Reusable workflow
  workflow_call:
    inputs:
      os:
        description: OS to use for testing
        required: true
        type: string
      python-version:
        description: Python version to use for testing
        required: true
        type: string
      pkg-artifact:
        description: Name of the package artifact
        required: true
        type: string


jobs:
  integration-test:
    name: Run integration tests
    runs-on: ${{ inputs.os }}
    env:
      TEST_DATASET_URL: 'https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/genes/hg38.refGene.gtf.gz'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Copy test script
        run: |
          mv repo/scripts/test/integration_test.sh .
          rm -rf repo/

      - name: Cache test dataset
        id: cache-test-dataset
        uses: actions/cache@v3
        with:
          # Note that the cache key only depends on the dataset URL.
          # This means that all jobs in the matrix will use the same cache entry.
          key: "test-dataset-${{ env.TEST_DATASET_URL }}"
          path: ${{ github.workspace }}/test_dataset.txt

      - name: Download test dataset
        # Download the test dataset only in case of cache misses
        if: steps.cache-test-dataset.outputs.cache-hit != 'true'
        run: curl -L "$TEST_DATASET_URL" | gzip -dc > test_dataset.txt

      # Download package generated by the make-package.yml workflow
      - name: Download package artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.pkg-artifact }}

      - name: Extract package
        run: |
          # Note: archived files reside in a folder named like: cryptonite-v1.2.3/
          tar -xf cryptonite-*/cryptonite-*.tar.xz --strip-components=1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache-dependency-path: pyproject.toml
          cache: pip

      - name: Create Python virtualenv
        run: python3 -m venv ./venv --upgrade

      - name: Install Cryptonite
        run: venv/bin/python3 -m pip install *cryptonite*.whl

      - name: Run integration test
        run: |
          # This script does the following:
          # - Encrypt file test_dataset.txt using key=18
          # - Decrypt the encrypted file using the same key
          # - Check that the original file and the decrypted file are identical
          
          ./integration_test.sh \
            venv/bin/cryptonite \
            test_dataset.txt    \
            18
